### ISSUE TITLE
No detect current active player in Plasma 6

### ISSUE THREAD

**Issue by warcayac** [ccatterina/plasmusic-toolbar#64]
When opening my browser with Youtube page by default, PT detcts the first video preview being played and the text displayed in PT stays there even when a new player (like Audacious) starts playing some music. 

![image](https://github.com/ccatterina/plasmusic-toolbar/assets/7342885/81d7691e-f362-47a7-86aa-32aaa48ceaa3)

So PT should auto-detect current active player or should be to able to give the chance to change between current players like Media player widget.

My info:
```
OS: EndeavourOS Linux x86_64
Kernel: 6.7.9-zen1-1-zen
Shell: zsh 5.9
Resolution: 3440x1440
DE: Plasma 6.0.1 (X11)
WM: KWin
Terminal: WarpTerminal
CPU: AMD Ryzen 7 1700 (16) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1070
Memory: 15905MiB
```

**Comment by ccatterina** [comment]
Hi!
yes, that's the expected behaviour. When `any` is selected as preferred source in the widget configuration, plasmusic should behave exactly like `Media Player` widget when you don't choose any player from the tab.

It should be nice to have a way to switch temporary between players like in the `Media Player`  widget! I add a new issue for this feature.

**Comment by ccatterina** [comment]
#65

**Comment by ccatterina** [comment]
I close this issue, feel free to reopen it if you have any further doubts about it.
