### ISSUE TITLE
 string scrolling causes high gpu usage

### ISSUE THREAD

**Issue by TheSnowfield** [ccatterina/plasmusic-toolbar#80]
When the mouse pointer hovers, the string starts scrolling on the toolbar, 
and then the GPU IRQs increase to 600 IRQs/s, 1200MHz frequency immediately; 

However, It's bringing my laptop heavy GPU usage to render this animation, why? It's just a text! 

![image](https://github.com/ccatterina/plasmusic-toolbar/assets/17957399/d245bf12-cbcb-4483-8fe8-294ba28d7b59)
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/17957399/a25488ec-4afa-4b69-aa00-b0af0e771dfe)

I'm using a 120Hz refresh rate display, so the GPU costs about 120 IRQs when the GPU is idle is a normal behavior.
I have tested, and this problem has nothing to do with the animation speed.

**Comment by ccatterina** [comment]
Hi @TheSnowfield 
Thank you for reporting this!

Maybe it's due the fact that I use clipping to create that animation: https://doc.qt.io/qt-6/qtquick-performance.html#clipping

https://github.com/ccatterina/plasmusic-toolbar/blob/2e8d520410eab58d19f830e373c4d06ca5ab2ddf/src/contents/ui/ScrollingText.qml#L39C1-L39C15


In the first version of the application the animation was implemented simply updating the text and it was probably better in terms of performance, but it was a bit snappy.

I'll try to improve the performance of the current implementation. If I can't I could add an option to switch to the old implementation, what do you think?

**Comment by TheSnowfield** [comment]
LGTM for adding a new option to switch the implementation. Thank you for your quick reply! :)

**Comment by ccatterina** [comment]
Hi @TheSnowfield 
I was a bit busy in this weeks and I couldn't investigate about this issue until today, I made some tests with plasmusic, I also tried to remove clipping and I had similar results.

Unfortunately, I don't know much about animations and gpu performance, so to see if the results were plausible for such an animation I compared them with a similar css animation in the browser [link](https://www.quackit.com/html/html_editors/scratchpad/preview.cfm?example=/css/codes/marquees/scrolling_text) . The performances seems not so different, could you try with the browser animation to see if you have the same result?

Anyway, I will try to reintroduce also the old scrolling animation mecanism, it needs some tweaking to be adapted to the new animation options, but I think I can do it in the next few weeks.

**plasmusic with stopped scrolling animation (2Mhz - 8irqs/s)**
![without scrolling-plasmusic](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/17597c4a-14cf-48f1-b193-3f8d46478323)

**plasmusic with running scrolling animation  (18Mhz - 477irqs/s)**
![plasmusic-with-scrolling](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/9202c998-cd0d-4c12-9284-9aecb2c3f175)

**Animation not running because the browser was opened in another tab   (13Mhz - 139irqs/s)**
![scrolling-text-2](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/0ec02bd0-c916-4f20-8fee-26370609804b)

**Animation running in the current tab (35Mhz - 696irqs/s)**
![scrolling-text-1](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/fa5e418f-7ab1-475b-9944-b155e986b4c7)

**Comment by ccatterina** [comment]
[Kooha-2024-04-02-18-50-11.webm](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/be9cc167-2f79-492e-b006-46cd7cf8bf9a)

**Comment by TheSnowfield** [comment]
I produced a fast check, I figured the problem was the Kwin force blur script, which forced all windows to have a blur backdrop effect(better appearance) finally increasing the draw calls. 

hmmmm... I have reproduced this problem on Chrome. I realized, so I turned off the blur script and disabled the opacity rule, the GPU frequency keeps 700MHz. Better.
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/17957399/c15f77cb-861f-45ed-851f-1d936f7d74a0)

The smooth animation went perfectly after adding the Plasma window to the blur script excepts list.  
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/17957399/21d7f96e-7430-42a2-9790-3a60c5c362c3)

Thank you for taking your time on this issue,  Cheers!
